### ISSUE TITLE
Class 'ILAB\MediaCloud\Cloud\Storage\StorageManager' not found in /htdocs/wp-content/plugins/ilab-media-tools/ilab-media-tools.php:90

### ISSUE THREAD

**Issue by stentotre** [Interfacelab/ilab-media-tools#37] opened 2018-10-30 10:38 UTC
We are running imgix and are uploading our images to S3. This has been working fine up until version 2.15 it seems (site has been in development for well over a year, with much of the same functionality.)

I was troubleshooting an issue where a few select images always returned a 403, so I disabled the secure URLS in imgix dashboard and inside the settings of the media cloud plugin. I also tweaked the cache expiration and set it to _public,max-age=86000_

When I saved these settings the site went into 500/white-screen, and this is what I have in my log:

`thrown in /htdocs/wp-content/plugins/ilab-media-tools/ilab-media-tools.php on line 90`

`[30-Oct-2018 10:21:50 UTC] PHP Fatal error:  Uncaught Error: Class 'ILAB\MediaCloud\Cloud\Storage\StorageManager' not found in /htdocs/wp-content/plugins/ilab-media-tools/ilab-media-tools.php:90`

**Stack trace:**
`#0 /wordpress-4.9.8/wp-settings.php(305): include_once()`
`#1 /htdocs/wp-config.php(54): require_once('/wordpress-4.9....')`
`#2 /htdocs/wp-load.php(37): require_once('/htdocs/wp-co...')`
`#3 /wordpress-4.9.8/wp-admin/admin.php(31): require_once('/htdocs/wp-lo...')`
`#4 /wordpress-4.9.8/wp-admin/index.php(10): require_once('/wordpress-4.9....')`
`#5 {main} thrown in /htdocs/wp-content/plugins/ilab-media-tools/ilab-media-tools.php on line 90`

**Comment by stentotre** [comment] 2018-10-30 10:39
I will try an earlier version to see if we get the same errors.

**Comment by jawngee** [comment] 2018-11-24 05:45
Bump

**Comment by DavidMillington-CD** [comment] 2019-06-13 17:44
What we found was that the version you install via the WordPress admin plugins system is 2.1.30 which only has very minor changes to 2.1.31 which is the latest on GitHub.  The version doesn't make a difference to this particular problem.  The issue is when you use the version from GitHub...

What was killing the GitHub version was that it lacks the vendor directory that the WordPress version includes.  So once you clone the GitHub repo make sure to run `composer install` in the plugin directory.

If that complains that "The "https://packages.interfacelab.io/packages.json" file could not be downloaded (HTTP/1.1 521 Origin Down)" it means that site is down which sucks.  I had this error.  The fix is easy.  Edit composer.json and remove the "repositories" block.  So ditch all of this and re-run the `composer install`:

```
"repositories": [{
    "type": "composer",
    "url": "https://packages.interfacelab.io"
  }],
```

**Comment by jawngee** [comment] 2019-06-13 17:51
The version in github is intended to be installed as a composer dependency via bedrock/trellis or whatever else you are using that manages WordPress via composer, so checking in the vendor directory would be a bad idea.

I just committed a change that removes the packages repo from the composer.json.  I'm not even sure why that was in there.

**Closed by jawngee** 2019-06-13 17:51 UTC

**Comment by DavidMillington-CD** [comment] 2019-06-14 07:37
We are installing it as a Git submodule.  Long story short we just inherited a project that installs all the WP plugins as submodules so to keep along the same line we did that with your plugin.  The site will be rewritten from the group up soon but the first step was to get the existing site up and running on our setup.

So the new pipeline is to install this as a submodule along with the others and then we call composer install in your plugin directory (after calling it in our main project root).  The commit you did to remove the package repo saves us some work, thank you.

**Comment by DavidMillington-CD** [comment] 2019-06-14 08:38
Since you implemented the change and bumped the version number can you make a 2.1.32 release please?

**Comment by jawngee** [comment] 2019-06-14 08:41
Done!

**Comment by DavidMillington-CD** [comment] 2019-06-14 09:25
Excellent, thank  you very much.
