### ISSUE TITLE
The issue is with creating unnecessary folders

### ISSUE THREAD

**Issue by RssInteractive** [Interfacelab/ilab-media-tools#226] opened 2024-01-22 15:23 UTC
Hello,

This plugin is not working properly on WordPress Version 6.4.2.

In the WordPress root directory (/var/www/html), it creates a folder named "https" and opens directories inside.

I tested this by deleting the folder and opening "Media" to upload a new image. I uploaded the image, and this directory was created.

The images are being uploaded to S3, so there is no issue with that.

Also, in the settings section:

An error occurs on line 261 in /var/www/********/wp-content/plugins/ilab-media-tools/lib/mcloud-illuminate/support/helpers.php:

Please help

******
Use php-fpm 8.1.19
Use centos

**Comment by jawngee** [comment] 2024-01-22 15:32
Can you create a reproduction.  This is kind of vague information you are providing.

Media Cloud doesn't write to the root directory anywhere in its codebase.  It's always to WP_CONTENT because that's the only predictably safe place to write files, so if you are seeing files written in your root wordpress directory something else is going on.

Please follow the issue template when filing bugs on github and provide a list of other plugins you are using.

I'm going to close this, but feel free to open a new issue with the issue template filled out.

Thanks,

Jon.

**Closed** 2024-01-22 15:32 UTC
