### ISSUE TITLE
Woocommerce srcset image sizes not on front-end since 3.0

### ISSUE THREAD

**Issue by gTaylorRokk** [Interfacelab/ilab-media-tools#106] opened 2020-02-21 16:10 UTC
**Describe the bug**
Our client noticed that their latest woocommerce product images were looking less sharp than they used to. When we investigated the front-end source it appears that not all the srcset sizes are being generated for new upload where they were before. See an example of old product image with srcset sizes generated versus new one uploaded recently without:

**Old**
![Screenshot 2020-02-21 at 16 03 27](https://user-images.githubusercontent.com/37620756/75050517-060c1600-54c4-11ea-9653-b396abefc8ff.png)

**New**
![Screenshot 2020-02-21 at 16 03 55](https://user-images.githubusercontent.com/37620756/75050542-12906e80-54c4-11ea-8be4-1b742d958d89.png)

I've checked the media files in the admin and all thumbnail sizes seem to be generated and linked in s3 bucket.

**To Reproduce**
1. Upload an image file via media uploader.
2. Assign image as featured image for a product.
3. Check source code on front-end for image srcset sizes.

**Comment by jawngee** [comment] 2020-02-21 16:40
Can you provide a dump of your image sizes (see `ilab_get_image_sizes()` in `helpers/ilab-media-tool-wordpress-helpers.php`).  print_r or json is acceptable.

can you also cut and paste the actual html of the image tag before/after, obfuscate the URLs if you have to.  images aren't particularly useful.

thanks!

**Comment by gTaylorRokk** [comment] 2020-02-21 17:00
Dump of image sizes as follows:

`Array ( [thumbnail] => Array ( [width] => 150 [height] => 150 [crop] => 1 ) [medium] => Array ( [width] => 300 [height] => 300 [crop] => ) [medium_large] => Array ( [width] => 768 [height] => 0 [crop] => ) [large] => Array ( [width] => 1024 [height] => 1024 [crop] => ) [1536x1536] => Array ( [width] => 1536 [height] => 1536 [crop] => [imgix] => ) [2048x2048] => Array ( [width] => 2048 [height] => 2048 [crop] => [imgix] => ) [thumb-200x100] => Array ( [width] => 200 [height] => 100 [crop] => [imgix] => ) [thumb-sq-200x200] => Array ( [width] => 200 [height] => 200 [crop] => 1 [imgix] => ) [sq-800x800] => Array ( [width] => 800 [height] => 800 [crop] => 1 [imgix] => ) [dh-thumbnail-square] => Array ( [width] => 600 [height] => 450 [crop] => 1 [imgix] => ) [dh-thumbnail] => Array ( [width] => 700 [height] => 350 [crop] => 1 [imgix] => ) [woocommerce_thumbnail] => Array ( [width] => 300 [height] => 0 [crop] => 0 [imgix] => ) [woocommerce_single] => Array ( [width] => 800 [height] => 0 [crop] => 0 [imgix] => ) [woocommerce_gallery_thumbnail] => Array ( [width] => 100 [height] => 100 [crop] => 1 [imgix] => ) [shop_catalog] => Array ( [width] => 300 [height] => 0 [crop] => 0 [imgix] => ) [shop_single] => Array ( [width] => 800 [height] => 0 [crop] => 0 [imgix] => ) [shop_thumbnail] => Array ( [width] => 100 [height] => 100 [crop] => 1 [imgix] => ) [wc_order_status_icon] => Array ( [width] => 32 [height] => 32 [crop] => 1 [imgix] => ) )`

Product image html:
<div class="product-images"> <a href="**************/"><div class="shop-loop-thumbnail"><noscript><img width="300" height="300" src="https://bdl-lon-bucket.s3-accelerate.amazonaws.com/2020/02/Bioflow-Sport-Flex-Navy-White-F-20-300x300.png" class="attachment-shop_catalog size-shop_catalog" alt="" /></noscript><img width="300" height="300" src="https://bdl-lon-bucket.s3-accelerate.amazonaws.com/2020/02/Bioflow-Sport-Flex-Navy-White-F-20-300x300.png" data-src="https://bdl-lon-bucket.s3-accelerate.amazonaws.com/2020/02/Bioflow-Sport-Flex-Navy-White-F-20-300x300.png" class="attachment-shop_catalog size-shop_catalog ls-is-cached lazyloaded" alt=""></div> </a><div class="shop-loop-quickview"><a data-product_id="86884" title="" href="****************" data-original-title="Quick view"><i class="fa fa-plus"></i></a></div></div>

**Comment by jawngee** [comment] 2020-02-21 17:02
Thanks!

You have to wrap the html in a code block though otherwise github mangles it:

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by gTaylorRokk** [comment] 2020-02-21 17:19
@jawngee Sorry, hopefully that works better now?

**Comment by jawngee** [comment] 2020-02-21 17:20
brilliant thanks

**Comment by jawngee** [comment] 2020-02-21 17:24
Is replace srcset enabled in your cloud storage settings?

![Screenshot of Safari (2-22-20, 12-23-57 AM)](https://user-images.githubusercontent.com/44449/75056455-a59fc780-5509-11ea-84f2-16f709f30787.png)

If it is, what happens when you turn it off?

**Comment by gTaylorRokk** [comment] 2020-02-21 17:45
Yes that setting was on:

![Screenshot 2020-02-21 at 17 40 14](https://user-images.githubusercontent.com/37620756/75057863-d5cb7400-54d1-11ea-81a6-4f6f4415d659.png)

If I switch it off nothing seems to change on the front-end. Older images still have srcset defined and the newer ones don't?

**Comment by jawngee** [comment] 2020-02-21 17:54
Ok, so I did the following:

- Create vanilla WP install
- Installed media cloud
- Installed woo
- Activated and setup woo
- Created product, set product image
- Viewed the shop page

On the front end I'm seeing the proper srcset:

```html
<img width="324" height="324" 
  src="https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048-324x324.png"  
  class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" 
  srcset="https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048-324x324.png 324w, 
  https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048-300x300.png 300w, 
  https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048-150x150.png 150w, 
  https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048-768x768.png 768w, 
  https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048-100x100.png 100w, 
  https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048-200x200.png 200w, 
  https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048-800x800.png 800w, 
  https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048-416x416.png 416w, 
  https://gutenberg-ilab-dev.s3-accelerate.amazonaws.com/2020/02/AGNB_WhiteShirt_2048x2048.png 900w" 
  sizes="(max-width: 324px) 100vw, 324px">
```

If I turn off media cloud entirely:

```html
<img width="324" height="324" 
  src="https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048-324x324.png" 
  class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" 
  srcset="https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048-324x324.png 324w, 
  https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048-300x300.png 300w, 
  https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048-150x150.png 150w, 
  https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048-768x768.png 768w, 
  https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048-100x100.png 100w, 
  https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048-200x200.png 200w, 
  https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048-800x800.png 800w, 
  https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048-416x416.png 416w, 
  https://mediacloud.test/app/uploads/2020/02/AGNB_WhiteShirt_2048x2048.png 900w" 
  sizes="(max-width: 324px) 100vw, 324px">
```

I see in your html you have data-srcset and some other stuff going on, but I'm not sure what that it is or what is generating those attributes.  But in a plain vanilla setup srcset output is identical to the default wordpress output.

**Comment by gTaylorRokk** [comment] 2020-02-21 17:59
@jawngee OK thanks. So are you thinking this is more likely a theme or conflicting plugin issue rather than your plugin not doing what it should be with srcset?

**Comment by jawngee** [comment] 2020-02-21 18:04
Hard to say, I'm like 85% certain it's not anything Media Cloud is doing, but I was pretty adamant about a bug earlier this week that I was wrong about, so I reserve some margin for being wrong.

However, if you have a dev environment, I'd be interested to know what happens when you turn off whatever it is you are using for lazy loading (which is what I'm assuming that data-srcset stuff is coming from).  But it could also be theme related too.  

If you can, open a ticket at https://support.mediacloud.press/submit-issue/ and send us the system report.  You can generate a system by turning on Media Cloud debugging in features, then clicking on Debug Log in the Media Cloud menu and clicking "Generate System Report".

I'm going to close this because I'm mildly certain it's not a bug but we can do more triage in a support ticket.

Thanks!

**Closed by jawngee** 2020-02-21 18:04 UTC

**Comment by gTaylorRokk** [comment] 2020-02-21 18:06
@jawngee OK, thanks for being so responsive on this. I'll test some things out locally and see what happens as suggested.

**Comment by jawngee** [comment] 2020-02-22 06:56
Just to follow up on this, I installed all the lazy load plugins I could find that had > 2000 installs on the wordpress.org repo (2000 is our testing threshold).

A few of them indeed clobber the srcset, but most did not.  Also, one thing to note, is that when you "inspect element" in chrome, it's showing the element's current attributes which may not be the same as what is in the source.  My thinking here is that the lazy load javascript assigning the srcset attributes might be affecting that in what chrome is showing you in the inspector.  Just a thought.

Are you using elementor or a page builder?

**Comment by gTaylorRokk** [comment] 2020-02-24 10:09
No it is a custom developed theme in this case.
